version: "3.9"
services:
  core-62tech:
    build: .
    command: ./bin/rest-service
    restart: on-failure
    ports:
      - 8915:8080
    environment:
      - APP_ENV=DEVELOPMENT
      - DEBUG=true
      - HTTP_PORT=8080
      - DB_HOST_MYSQL=db-62tech
      - DB_PORT_MYSQL=3306
      - DB_USER_MYSQL=root
      - DB_PASSWORD_MYSQL=mauFJcuf5dhRMQrjj
      - DB_NAME_MYSQL=db62tech
      - DB_MAX_IDLE_CONN=10
      - DB_MAX_OPEN_CONN=10
    networks:
      - 62tech
    depends_on:
      - db-62tech
  db-62tech:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - 3388:3306
    environment:
      - MYSQL_DATABASE=db62tech
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    networks:
      - 62tech

  adminer-62tech:
    image: adminer
    restart: always
    ports:
      - 8072:8080
    networks:
      - 62tech

networks:
  62tech:
    driver: bridge
